# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_image', models.FileField(default='null', upload_to='./upload')),
                ('price', models.ImageField(default=1, upload_to='')),
                ('play', models.CharField(choices=[('Y', 'play'), ('N', 'not play')], default='N', max_length=100)),
            ],
        ),
    ]
